spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DATABASE}?useTimezone=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: optional:file:.env[.properties]